# 94_ML 실습02 - good_books 1

[Good_books-10k dataset](https://www.kaggle.com/datasets/zygmunt/goodbooks-10k)

In [6]:
import numpy as np 
import pandas as pd

import os
print(os.listdir('./Datasets/goodbooks/'))

['book_tags.csv', 'sample_book.xml', 'tags.csv', 'ratings.csv', 'to_read.csv', 'books.csv']


In [7]:
# books.csv
books = pd.read_csv('./Datasets/goodbooks/books.csv', encoding = 'ISO-8859-1')
books.head()

id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
1   2        3             3  4640799          491  439554934  9.780440e+12   
2   3    41865         41865  3212258          226  316015849  9.780316e+12   
3   4     2657          2657  3275794          487   61120081  9.780061e+12   
4   5     4671          4671   245494         1356  743273567  9.780743e+12   

                        authors  original_publication_year  \
0               Suzanne Collins                     2008.0   
1  J.K. Rowling, Mary GrandPré                     1997.0   
2               Stephenie Meyer                     2005.0   
3                    Harper Lee                     1960.0   
4           F. Scott Fitzgerald                     1925.0   

                             original_title  ... ratings_count  \
0                          The Hunger Games  ...       4780653   
1  Harry Potter and the Philosopher's Stone  ...       4602479   
2                                  Twilight  ...       3866839   
3                     To Kill a Mockingbird  ...       3198671   
4                          The Great Gatsby  ...       2683664   

  work_ratings_count  work_text_reviews_count  ratings_1  ratings_2  \
0            4942365                   155254      66715     127936   
1            4800065                    75867      75504     101676   
2            3916824                    95009     456191     436802   
3            3340896                    72586      60427     117415   
4            2773745                    51992      86236     197621   

   ratings_3  ratings_4  ratings_5  \
0     560092    1481305    2706317   
1     455024    1156318    3011543   
2     793319     875073    1355439   
3     446835    1001952    1714267   
4     606158     936012     947718   

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...   
1  https://images.gr-assets.com/books/1474154022m...   
2  https://images.gr-assets.com/books/1361039443m...   
3  https://images.gr-assets.com/books/1361975680m...   
4  https://images.gr-assets.com/books/1490528560m...   

                                     small_image_url  
0  https://images.gr-assets.com/books/1447303603s...  
1  https://images.gr-assets.com/books/1474154022s...  
2  https://images.gr-assets.com/books/1361039443s...  
3  https://images.gr-assets.com/books/1361975680s...  
4  https://images.gr-assets.com/books/1490528560s...  

[5 rows x 23 columns]

In [11]:
# ratings.csv
ratings = pd.read_csv('./Datasets/goodbooks/ratings.csv', encoding = 'ISO-8859-1')
ratings.head()

book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [12]:
# book_tags.csv
book_tags = pd.read_csv('./Datasets/goodbooks/book_tags.csv', encoding = 'ISO-8859-1')
book_tags.head()

goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [16]:
# tags.csv
tags = pd.read_csv('./Datasets/goodbooks/tags.csv',)
tags.tail()

tag_id    tag_name
34247   34247   Ｃhildrens
34248   34248   Ｆａｖｏｒｉｔｅｓ
34249   34249       Ｍａｎｇａ
34250   34250      ＳＥＲＩＥＳ
34251   34251  ｆａｖｏｕｒｉｔｅｓ

In [17]:
# book_tags와 tags를 merge
tags_join_DF = pd.merge(book_tags, tags, left_on='tag_id', right_on = 'tag_id', how='inner')
                    # 합치기
                        # left DF
                                    # right DF
                                        # left_on : Column or index level names to join on in the left DataFrame.
                                                            # right_on : Column or index level names to join on in the right DataFrame.
                                                                                # how : Type of merge to be performed. default inner
                                                                                    # left: use only keys from left frame, similar to a SQL left outer join; preserve key order.
                                                                                    # right: use only keys from right frame, similar to a SQL right outer join; preserve key order.
                                                                                    # outer: use union of keys from both frames, similar to a SQL full outer join; sort keys lexicographically.
                                                                                    # inner: use intersection of keys from both frames, similar to a SQL inner join; preserve the order of the left keys.
                                                                                    # cross: creates the cartesian product from both frames, preserves the order of the left keys.
tags_join_DF.head()

goodreads_book_id  tag_id   count tag_name
0                  1   30574  167697  to-read
1                  2   30574   24549  to-read
2                  3   30574  496107  to-read
3                  5   30574   11909  to-read
4                  6   30574     298  to-read

In [19]:
to_read = pd.read_csv('./Datasets/goodbooks/to_read.csv')
to_read

user_id  book_id
0             1      112
1             1      235
2             1      533
3             1     1198
4             1     1874
...         ...      ...
912700    53424     4716
912701    53424     4844
912702    53424     5907
912703    53424     7569
912704    53424     8859

[912705 rows x 2 columns]

In [20]:
# books의 authors 
books['authors'][:5]

0                 Suzanne Collins
1    J.K. Rowling, Mary GrandPré
2                 Stephenie Meyer
3                      Harper Lee
4             F. Scott Fitzgerald
Name: authors, dtype: object

In [21]:
# authors 로 Tfidf 수행
from sklearn.feature_extraction.text import TfidfVectorizer
                                            # TfidVectorizer : Convert a collection of raw documents to a matrix of TF-IDF features

tf = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(books['authors'])
tfidf_matrix

<10000x14742 sparse matrix of type '<class 'numpy.float64'>'
	with 43235 stored elements in Compressed Sparse Row format>

In [22]:
# 유사도 측정
from sklearn.metrics.pairwise import linear_kernel
                                        # linear_kernel : Compute the linear kernel between X and Y.

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
cosine_sim[0]

array([1., 0., 0., ..., 0., 0., 0.])

In [24]:
# The Hobbit 의 index는 6
titles = books['title']
indices = pd.Series(books.index, index=books['title'])
            # Series : One-dimensional ndarray with axis labels (including time series).
indices['The Hobbit']

6

In [25]:
# 유사도 값 호출
cosine_sim[indices['The Hobbit']]

array([0., 0., 0., ..., 0., 0., 0.])

In [26]:
# 유사도 결과를 인덱스를 가진 list 형으로
cosine_sim[indices['The Hobbit']].shape

(10000,)

In [31]:
list(enumerate(cosine_sim[indices['The Hobbit']]))[:10]

[(0, 0.0),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 1.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0)]

In [29]:
# 가장 유사한 책의 인덱스 찾기
sim_scores = list(enumerate(cosine_sim[indices['The Hobbit']]))
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
            # sorted : 받은 Iterable 을 정렬하여 돌려줌
                    # Iterable data
                                # key : 기준이 되는 key 값을 지정 // lambda x : x[1] == [0.0, 1.0] 을 기준으로 잡겠다는 뜻
                                                    # reverse : 내림차순 적용 여부 확인
sim_scores[:3]

[(6, 1.0), (18, 1.0), (154, 1.0)]

In [32]:
# 작가로 본 유사 책 검색
sim_scores = sim_scores[1:11]
book_indices = [i[0] for i in sim_scores]
titles.iloc[book_indices]

18      The Fellowship of the Ring (The Lord of the Ri...
154            The Two Towers (The Lord of the Rings, #2)
160     The Return of the King (The Lord of the Rings,...
188     The Lord of the Rings (The Lord of the Rings, ...
963     J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
4975        Unfinished Tales of Númenor and Middle-Earth
2308                               The Children of Húrin
610              The Silmarillion (Middle-Earth Universe)
8271                   The Complete Guide to Middle-Earth
1128     The History of the Hobbit, Part One: Mr. Baggins
Name: title, dtype: object

In [33]:
# book에 tag 포함
books_with_tags = pd.merge(books, tags_join_DF, left_on = 'book_id',
                            right_on = 'goodreads_book_id', how='inner')
books_with_tags.head()

id  book_id  best_book_id  work_id  books_count       isbn        isbn13  \
0   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
1   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
2   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
3   1  2767052       2767052  2792775          272  439023483  9.780439e+12   
4   1  2767052       2767052  2792775          272  439023483  9.780439e+12   

           authors  original_publication_year    original_title  ...  \
0  Suzanne Collins                     2008.0  The Hunger Games  ...   
1  Suzanne Collins                     2008.0  The Hunger Games  ...   
2  Suzanne Collins                     2008.0  The Hunger Games  ...   
3  Suzanne Collins                     2008.0  The Hunger Games  ...   
4  Suzanne Collins                     2008.0  The Hunger Games  ...   

  ratings_2 ratings_3  ratings_4  ratings_5  \
0    127936    560092    1481305    2706317   
1    127936    560092    1481305    2706317   
2    127936    560092    1481305    2706317   
3    127936    560092    1481305    2706317   
4    127936    560092    1481305    2706317   

                                           image_url  \
0  https://images.gr-assets.com/books/1447303603m...   
1  https://images.gr-assets.com/books/1447303603m...   
2  https://images.gr-assets.com/books/1447303603m...   
3  https://images.gr-assets.com/books/1447303603m...   
4  https://images.gr-assets.com/books/1447303603m...   

                                     small_image_url  goodreads_book_id  \
0  https://images.gr-assets.com/books/1447303603s...            2767052   
1  https://images.gr-assets.com/books/1447303603s...            2767052   
2  https://images.gr-assets.com/books/1447303603s...            2767052   
3  https://images.gr-assets.com/books/1447303603s...            2767052   
4  https://images.gr-assets.com/books/1447303603s...            2767052   

   tag_id  count           tag_name  
0   30574  11314            to-read  
1   11305  10836            fantasy  
2   11557  50755          favorites  
3    8717  35418  currently-reading  
4   33114  25968        young-adult  

[5 rows x 27 columns]